### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by Tristans-sky** [DV8FromTheWorld/JDA#1065]
- [x ] I have checked for similar issues.
- [x ] I have updated to the [latest JDA version][download].

## Feature Request

I want to disable logging. However i didn´t found anything .

### Example Use-Case

i think this explains a lot:
https://i.imgur.com/Faz6Mcw.png

**Comment by Andre601** [comment]
The issue tracker is not for questions.

**Comment by MinnDevelopment** [comment]
I'll present you with a few options:

- [Logback Configuration](https://logback.qos.ch/manual/configuration.html)
- [Log4j Configuration](https://logging.apache.org/log4j/2.x/manual/configuration.html)
- [Ask on Stackoverflow](https://stackoverflow.com/questions/ask)

This is completely unrelated to JDA since we only use the SLF4J provided api and don't provide any logger implementation/configuration.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by Tristans-sky** [comment]
So my problem is that when i include jda via maven it doesn´t give me any org.apache.logging.log4j Logger. So i can´t fix this. This is why i opened this

**Comment by MCOfficer** [comment]
just to clarify minn's comment: you need to add JDA *and* a logger such as log4j
