### ISSUE TITLE
ERROR JDA - One of the EventListeners had an uncaught exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Mikenator** [DV8FromTheWorld/JDA#1070]
Hey, 

when I enter a command it doesn't work and the issue:

`ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException`

is in the console. 

I saw the post with the same issue, but it doesn't helped me, so I make a new. 

Sorry for my bad English xd 

I would be happy if you can help me,
Greats, 
Mikenator

**Comment by TheDGOfficial** [comment]
You didn't even post the full stack trace, code and JDA version. And this not the place for help. Go to JDA's Discord Server to get help.

https://discord.gg/0hMr4ce0tIl3SLv5

**Comment by MinnDevelopment** [comment]
Looks like an error in your code, read the stacktrace and use a debugger.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
