### ISSUE TITLE
Problem with getting things

### ISSUE THREAD

**Issue by Siebrenvde** [DV8FromTheWorld/JDA#1104]
Hello

I have written some code using JDA.
While updating it to the latest version of JDA, I got some errors with getTextChannelById, getAuthor, getContentRaw & getChannel.

Here's the code:
```java
public void sendMessage(String message, String channelID) {
        TextChannel tc = bot.getJda().getTextChannelById(channelID);
        tc.sendMessage(message).queue();
    }

    public void sendEmbed(String title, String description, String channelID) {
        TextChannel tc = bot.getJda().getTextChannelById(channelID);
        tc.sendMessage(new EmbedBuilder().setTitle(title).setDescription(description).build()).queue();
    }

    private void staffChat(DiscordBotCommand command) {
        User user = command.getMessage().getAuthor();
        String msg = command.getMessage().getContentRaw();
        if(msg.length() < 2) {
            command.getMessage().getChannel().sendMessage("**Usage**: ***-sc <message>***").queue();
        } else {
            Utils.sendPermissionMessage(Main.plugin.minecraftLayout(msg, user), "staffchat.see");
        }
    }
```

I don't get what's wrong and haven't found anyone else with the same issues.

**Comment by MinnDevelopment** [comment]
> I got some errors

Yes that's completely useless information by itself. How are we supposed to help when the issue is not even known.

Also, this is not a bug report or feature request. You can [join the discord server](https://discord.gg/0hMr4ce0tIl3SLv5) to receive support or [ask questions on StackOverflow](https://stackoverflow.com/questions/ask).
