### ISSUE TITLE
Recognize AllContributors in the README

### ISSUE THREAD

**Issue by DV8FromTheWorld** [DV8FromTheWorld/JDA#1123]
We should start using https://github.com/all-contributors/all-contributors to fully recognize the people who contribute to this project, both with code and via answering questions.

**Comment by Andre601** [comment]
Seems like an interesting idea and I'm sure there are a lot of people that helped out in more than just code-stuff and PRs

**Comment by kantenkugel** [comment]
Answering questions might be a bit interesting due to a lot of ppl also answering in the Discord server and we can't really keep track of those, while still being on the same contribution level (or imo even helping "better") as those in issues.

I wouldn't mind keeping track of all PR contributors tho (but maybe not via the bot or at least not with those categories... i don't really like the proposed emoji key)
