### ISSUE TITLE
LOADING_SUBSYSTEMS doesn't reset to CONNECTED on reconnect

### ISSUE THREAD

**Issue by TheEpTic** [DV8FromTheWorld/JDA#116]
After a few hours of operation, my bot will disconnect from Discord randomly.

Upon reconnect, JDA will setup everything as usual and will change it's status as it should. Once it's ready, it should set it to "CONNECTED" but it doesn't. It'll sometimes find it's self stuck on "LOADING_SUBSYSTEMS" but JDA will be operational. Responding to commands, processing data.

I'm not exactly sure what this could be but I'm guessing upon reconnect it's failing to set it's status. Everything else seems fine.

Running 5 shards with around 900 guilds per shard if that helps anything. Could be a sharding issue, not sure.

Image: https://i.imgur.com/h67Uonb.png

**Comment by DV8FromTheWorld** [comment]
@Fabricio20 you also run a sharded bot, can you confirm this?

**Comment by Fabricio20** [comment]
Sure thing.

**Comment by DV8FromTheWorld** [comment]
I cannot seem to reproduce this.
Using a bot connected to 2 guilds, I've attempted the following:
Login -> Force a RESUME due to internet loss. Bug unseen.
Login -> Force a RECONNECT due to internet loss. Bug unseen.
Login w/ Sharding -> Force a RESUME due to internet loss. Bug unseen.
Login w/ Sharding -> Force a RECONNECT due to internet loss. Bug unseen.

I cannot figure out how you've encountered this issue.

**Comment by DV8FromTheWorld** [comment]
I need more information before I can fix this.

**Comment by DV8FromTheWorld** [comment]
Based on initial testing, it looks like this coincides with Resume not being fired properly.

**Comment by TheEpTic** [comment]
JDA 2 no longer has support along with everybody shifting off it. This shouldn't be a problem for JDA 3 considering it's been completely rewritten.

Closing.
