### ISSUE TITLE
Add/Remove Role

### ISSUE THREAD

**Issue by CheeseTastisch** [DV8FromTheWorld/JDA#1193]
Hey, I use `Discord.getDiscord().removeRoleFromMember(member, Discord.getDiscord().getRoleById(667810662684295219L));` 
Discord.getDiscord() returns my Guild(This works). 
But the Bot dosn´t Remove the Member the Role. In the Console isn´t any Error.
And the Bot has alle Rights and is in the higest group.

Sorry for my bad Englich, but I am from Germany.

**Comment by duncte123** [comment]
This is because `removeRoleFromMember` returns a RestAction.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by CheeseTastisch** [comment]
Tanke you, and sorry, but I Was think it is a bug. Thats the reason why I make this issus

**Comment by DV8FromTheWorld** [comment]
[Wiki entry on RestActions](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction)
