### ISSUE TITLE
Message Update Event

### ISSUE THREAD

**Issue by marko-pilipovicc** [DV8FromTheWorld/JDA#1197]
### I've had a look around and can't seem to find an answer. The discord JS library offers you to see both the new and old message content but I can't seem to be able to get the old content. It would be nice to be able to get the old content of a message before it was edited.

Something like
onMessageUpdate(MessageUpdateEvent event) {
String oldContent = event.getMessage().getPreviousContent();
System.out.println(oldContent);
}

**Comment by Andre601** [comment]
You have to cache the message yourself as JDA won't do that by itself...
And in addition to all the stuff that is already cached/loaded would caching messages increase the RAM usage a lot (from what I understand.

Also, please follow the issue-templates. They're here for a reason.

**Comment by DV8FromTheWorld** [comment]
Continuing what @Andre601 was saying: the JS library for Discord has an internal cache of previously received messages. With this cache, it can provide the old content of a message when it receives the _new_ content. This cache only goes as far back as when the bot connected to the gateway. As such, messages updated that were sent _before_ the bot connected to the gateway would result in `null` for the `getPreviousContent()`.

JDA does not provide this functionality due to this reason and also because caching of messages would consume a ton of resources. As such, we have left the concern of message caching to be solved by userland use cases.
