### ISSUE TITLE
Add more sub-interfaces to Events for easier handling in custom EventListener implementations

### ISSUE THREAD

**Issue by Atakku** [DV8FromTheWorld/JDA#1246]
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

Breakdown big event interfaces into smaller ones, and make them implement multiple smaller interfaces

Example:
GenericSnowflakeEvent -> implements the getId() and getIdLong()
GenericUserEvent -> implements the getUser()/getAuthor()
and more

### Example Use-Case

In custom event listeners, this would allow for way shorter code
Personally, I'm writing an annotation based EventListener which also has FilterAnnotations, and the only way i can filter events by user now, is checking if it extends any event which has the getUser or getAuthor methods, which makes it horribly long, and it would require a lot of maintenance in order to keep it up to date with JDA

**Comment by Andre601** [comment]
I myself think this is a pretty rare use-case to justify such an implementation.
There are currently things like the `ListenerAdabter` which already extends the `GenericEvent` or other more casual event types.

If you didn't check already, you might wanna take a look at the [list of events](https://github.com/DV8FromTheWorld/JDA/wiki/8%29-List-of-Events) on the wiki.

**Comment by MinnDevelopment** [comment]
I don't see how this would be possible without breaking changes.

**Comment by MinnDevelopment** [comment]
Nevertheless, I think the trade-off for shorter code is not as great. We would introduce a lot more complexity to the event system for little gain. You can already capture very generic event types such as GenericEvent and GenericMessageEvent etc. This would introduce more complexity in the code and make things harder to understand for user and maintainer. Another issue is naming, I don't wanna make 300 interfaces that have a single method like "GetUserInterface" which adds "getUser()". There really is no benefit there since you can already check if a method exists using reflections. Making an interface for individual methods of the events is a non-goal and I have to decline.

**Comment by DV8FromTheWorld** [comment]
> you can already check if a method exists using reflections

Yeah, this is also what I'd recommend to simplify your code and make it forwards compatible for new events in the future.

**Comment by Atakku** [comment]
i have only one issue with that, in some events to get the user who triggered the event its getAuthor() and in other its getUser()

**Comment by DV8FromTheWorld** [comment]
That's a valid concern, however, that should be easily handleable by checking for both `getUser` and `getAuthor`
