### ISSUE TITLE
Problem with event.getMember

### ISSUE THREAD

**Issue by Mrolcraft** [DV8FromTheWorld/JDA#1261]
Hello, I try to make a bot, but I have a problem and I think it's a bug of JDA. 

 `    @Override
    public void onMessageReactionRemove(MessageReactionRemoveEvent event) {
        if(event.getUser().isBot()) return;
        boolean nil = (event.getMember() == null);
        System.out.println(nil);
   }`

This code return me true so event.getMember() is null but in the next code event.getMember() != null so can you explain me why the first code return me null and the second not null thanks you

 `    @Override
    public void onMessageReactionAdd(MessageReactionAddEvent event) {
        if(event.getUser().isBot()) return;
        boolean nil = (event.getMember() == null);
        System.out.println(nil);
    }`

**Comment by Andre601** [comment]
Please use the issue templates next time since they exist for a reason.
Additionally use code blocks next time as inline code is horrible to read when it looks like that.

To your issue: `MessageReactionAddEvent` is not just for reactions being added on Discord servers, but also on DMs, which do not have Members, so `event.getMember()` can return both null and not null (the actual Member)
If you want to use the event only for Guilds, use the [GuildMessageReactionAddEvent](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionAddEvent.html) and for private chat the [PrivateMessageReactionAddEvent](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/message/priv/react/PrivateMessageReactionAddEvent.html)

This is in no way a bug (as far as I can tell) and you should join the JDA Discord for faster support: https://discord.gg/0hMr4ce0tIk3pSjp

**Comment by Mrolcraft** [comment]
I tried with GuildMessageReactionRemoveEvent and event.getMember() return null again and normally it must return a result not null

**Comment by DManstrator** [comment]
I'm pretty sure the Member is not cached by JDA because of the CacheFlag or Intents so you get null. Because for that reason you are supposed to tell us how you build your JDA instance with the issue template. Set the MemberCacheFlag to ALL and add the needed intents and see if that still happens.

**Comment by Mrolcraft** [comment]
```
 this.bot = JDABuilder.createDefault(Utils.BOT_TOKEN)
                .setMemberCachePolicy(MemberCachePolicy.ALL)
                .setEnabledIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_VOICE_STATES, GatewayIntent.GUILD_EMOJIS, GatewayIntent.GUILD_MESSAGES, GatewayIntent.GUILD_MESSAGE_REACTIONS)
                .build();
```

So I set the `MemberCacheFlag` to `ALL` and I added the needed intents but it still doesn't work I tried with `MessageReactionRemoveEvent` and `GuildMessageReactionRemoveEvent` but it doesn't change anything, event.getMember() always returns null.

**Comment by Andre601** [comment]
Did you make sure to enable the Member intent in the developer Panel?
It is required to do this:
https://andre601.github.io/JDA-Wiki/usage/gatewayintents/#privileged-intents

**Comment by DManstrator** [comment]
You might need to set the `ChunkingFilter` to `ALL` too. We had a similar issue in the Discord server right now and this solved the problem.

**Comment by Mrolcraft** [comment]
Yes all of privileged intents are enabled, I've added the ChunkingFilter and it works, thank you very much.
