### ISSUE TITLE
Support for discord flags

### ISSUE THREAD

**Issue by Bas950** [DV8FromTheWorld/JDA#1265]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

https://discordapp.com/developers/docs/resources/user#user-object-user-flags

**Comment by duncte123** [comment]
This is not implemented because bots do not receive this data.

**Comment by MinnDevelopment** [comment]
Please fill out the entire issue template.

**Comment by Andre601** [comment]
As @duncte123 mentions are those flags not available for bots by default.
It requires your bot to ask for the `Identify` Flag in its OAuth2 invite. See the `Required OAuth2 Scopes` in the [User Object section](https://discordapp.com/developers/docs/resources/user#user-object) which was just above the one you mentioned.

And JDA is a library made for bot-development so managing any scope other than the ones required for running a bot seems useless for me.
Especially since other libs/add-ons like [JDA-Utilities](https://github.com/JDA-Applications/JDA-Utilities) exist, which provide Support for handling additional OAuth2 Scopes.

@duncte123 Maybe he means [Public Flags](https://github.com/discord/discord-api-docs/pull/1490) tho?

**Comment by Bas950** [comment]
I mean these 2:
![image](https://user-images.githubusercontent.com/34792838/79641865-5dfc8b80-819a-11ea-95a2-89bc73d6befd.png)

**Comment by Andre601** [comment]
Those aren't public by default.
As I stated before do they require your bot to ask for the Identify scope in the OAuth invite.

**Comment by Bas950** [comment]
:feelsbadman:

**Comment by boomboompower** [comment]
> Those aren't public by default.
> As I stated before do they require your bot to ask for the Identify scope in the OAuth invite.

Try modifying the EntityBuilder class [here](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java#L347) append a System.out.println call to `user.getInt("public_flags", 0)`

Here is the output for my bot which has no OAuth scopes
```{"public_flags":64,"id":"123456789098765432","avatar":"6e9a40be61.trimmed.2d188621ac57","username":"username","discriminator":"0466"}```

Not all users have them but some do
