### ISSUE TITLE
Webhook Events

### ISSUE THREAD

**Issue by SkyLicks** [DV8FromTheWorld/JDA#1330]
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

Please add JDA events that listen to the following actions relating to webhooks:
- Webhook creation
- Webhook deletion
- Webhook modification

At this time, JDA has no events relating to webhook. Its a feature at least I would find useful.

**Comment by MinnDevelopment** [comment]
This isn't possible because discord doesn't have events for this. The only even discord has is a [`WEBHOOKS_UPDATE`](https://discord.com/developers/docs/topics/gateway#webhooks-update) which only tells you the webhooks on a channel changed, not what has changed.

You can use that event by enabling raw events and handling the raw event:

```java
JDABuilder.createDefault(token)
    .setRawEventsEnabled(true)
    .addEventListeners(new RawEventHander())
    .build();

class RawEventHandler extends ListenerAdapter {
    @Override
    public void onRawGateway(RawGatewayEvent event) {
        if (!event.getType().equals("WEBHOOKS_UPDATE")) return;
        DataObject payload = event.getPayload();
        long channelId = payload.getLong("channel_id");
        TextChannel channel = event.getJDA().getTextChannelById(channelId);
        // check what changed
    }
}
```

We can't add events for this without discord sending us a useful gateway event.

You can make a feature request by opening an issue [here](https://github.com/discord/discord-api-docs/issues/new)
