### ISSUE TITLE
Guild.getMember(User) returns null only with JDABuilder().createDefault() or .createLight()

### ISSUE THREAD

**Issue by tuxnull** [DV8FromTheWorld/JDA#1414]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The getMember(User) method returns null when JDABuilder is created with the Default or Light Caching settings and even after setting the MemberCachePolicy.

### Expected Behavior

When using the now deprecated `new JDABuilder();` to create my JDA objects, Guild.getMember(User) works fine and returns the Member object of the related user.

### Code Example or Reproduction Steps

`JDABuilder builder = JDABuilder.createDefault(api_key);
builder.setMemberCachePolicy(MemberCachePolicy.ONLINE);`

### Code for JDABuilder or DefaultShardManagerBuilder Used

s.a.

### Exception or Error

Object is null which causes a NPE later on.

**Comment by MinnDevelopment** [comment]
This is intended behavior. As the docs mention, `MemberCachePolicy.ONLINE` requires `GatewayIntent.GUILD_PRESENCES` to function. So you have to do `builder.enableIntents(GatewayIntent.GUILD_PRESENCES)`. Note that `MemberCachePolicy.ONLINE` will not be supported in future versions due to breaking changes in API v8. In the future, you have to use `guild.retrieveMembersByIds(...)` to load presences at runtime.
