### ISSUE TITLE
getMembers method doesn't counting members in guild

### ISSUE THREAD

**Issue by OMAR-3OOV** [DV8FromTheWorld/JDA#1435]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
Members in guild doesn't count

### Code Example or Reproduction Steps
Guild#getMembers
Guild#getMemberById

### Exception or Error
NullPointerException

**Comment by Andre601** [comment]
This is an expected behaviour as JDA doesn't cache members when using createDefault or createLight.

Use the retrieve methods instead.

**Comment by MCOfficer** [comment]
You need to post the full stacktrace. Also, please post the *exact* code that triggers this problem. 

If i had to guess, i'd say Guild is null for one reason or the other (JDA not initialized, bot not in the guild in question, ID wrong).

**Comment by MinnDevelopment** [comment]
Since you omitted the JDABuilder code I can only assume. You don't have chunking enabled. Your reproduction steps are extremely lacking so I can't do anything here. You didn't even bother to include the stacktrace of your exception.

Try using `retrieveMemberById` and `getMemberCount`.

Closing because this issue has no useful information to go on.
