### ISSUE TITLE
Role missing when managed by Carl-bot

### ISSUE THREAD

**Issue by rocambin** [DV8FromTheWorld/JDA#1480]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behavior

Getting a member's role managed by `Carl-bot` (_automatic welcoming role_).

### Code Example or Reproduction Steps

```Java
// The role managed by Carl-bot is missing
getRoles().stream().map(Role::getName).forEach(name -> sout(name))
```

### Code for JDABuilder or DefaultShardManagerBuilder Used

> N/A

### Exception or Error

> N/A

**Comment by Horstexplorer** [comment]
What is even the issue?

**Comment by MinnDevelopment** [comment]
Can't reproduce.

**Comment by DManstrator** [comment]
There was a discussion about it a month ago in the [JDA Discord](https://discord.com/channels/125227483518861312/125227483518861312/779427714532638791). Afaik it is a race condition where Carl Bot gives a role to a member after they joined but when the own bot gets the event, it doesn't have the role at that point (which makes sense since both bots get the same event and react to it).

I guess the only solution for it is to re-fetch the member from Discord.
