### ISSUE TITLE
Can't change bot's visibility?

### ISSUE THREAD

**Issue by SpaceByteDev** [DV8FromTheWorld/JDA#1507]
All I need to do is simply change the bot's visibility. First thing I tried is this:
`jda.setStatus(OnlineStatus.DO_NOT_DISTURB);`
The variable dja, is my JDABuilder, btw.
I've also tried adding a build after that, just to see.
I cannot get anything to work. Any help?

**Comment by RedstonecraftHD** [comment]
Could you attach the full code of your Class?

**Comment by MinnDevelopment** [comment]
Before calling build you can set it with [JDABuilder#setStatus](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setStatus(net.dv8tion.jda.api.OnlineStatus)) and then afterwards you can set it with [JDA#getPresence](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#getPresence()) and [Presence#setStatus](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/managers/Presence.html#setStatus(net.dv8tion.jda.api.OnlineStatus)).

You can also find this in the [FAQ](https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ#how-can-i-change-the-playing) and its documented by [JDABuilder#setStatus](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setStatus(net.dv8tion.jda.api.OnlineStatus)) as well:

> This value can be changed at any time in the Presence from a JDA instance.

Closing due to #1337
