### ISSUE TITLE
The jda.getUsers() doesnt get every user

### ISSUE THREAD

**Issue by SageSphinx63920** [DV8FromTheWorld/JDA#1544]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behavior

If i use jda.getUsers().forEach(); , jda only get the self user on some servers. The problem is when i want to make something like a global giveaway(just a example) i cant get evey user or when i but the .size() behind it, that i can show how many people are useing the bot, it give me a 11 instead of  20000

### Code Example or Reproduction Steps

Start your bot with JDABuilder and make jda.getUsers()

### Code for JDABuilder or DefaultShardManagerBuilder Used

public static JDA jda;
public static JDABuilder builder;

builder = JDABuilder.createDefault(donotopen.token);
builder.setAutoReconnect(true);

try {
	jda = builder.build();			
	} catch (Exception e) {
	e.printStackTrace();
	}	
### Exception or Error

N/A

**Comment by SageSphinx63920** [comment]
Its my firt Issuse. I hope everything is ok

**Comment by arynxd** [comment]
JDA#getUsers is a cache only operation, this is not a bug.

**Comment by MinnDevelopment** [comment]
Please read this [Gateway Intents and Member Cache Policy](https://github.com/DV8FromTheWorld/JDA/wiki/Gateway-Intents-and-Member-Cache-Policy). Users are not loaded into cache by default. You shouldn't rely on that unless you absolutely have to.

> i can show how many people are useing the bot

`getUsers()` returns all users that happen to be cached, not just the ones using your bot. So that count would be misleading and wrong.

Closing as intended behavior.
