### ISSUE TITLE
Trigger join & leave guild not work? 

### ISSUE THREAD

**Issue by GamerBoomTV** [DV8FromTheWorld/JDA#1610]
Hello,
I use the discord jda version 4.2.1_253. I'm trying a lot with the triggers, but nothing happen:

- Member joined a Guild
- Member leave a Guild

This triggers didn't work - please check it.

I open this thread as a question, if my thinks are right, please make a bug report.

Thanks a lot
Dan

**Comment by MCOfficer** [comment]
You can get support on the JDA discord server, this issue will probably be closed because of #1337 

https://discord.gg/0hMr4ce0tIk3pSjp

**Comment by Andre601** [comment]
A few things:

1. You're outdated. The latest version of JDA is `4.2.1_261` so please update
2. You don't give any real information about what you tried so far. Did you actually enable and use the GUILD_MEMBER intent? It's required for Join and Leave Events to work.
3. Your issue doesn't follow the template at all. If you have general questions, better ask them on the [JDA Discord Server](https://discord.gg/jda) or [open a Discussion on this repository](https://github.com/DV8FromTheWorld/JDA/discussions)

**Comment by MinnDevelopment** [comment]
Troubleshooting Guide: [My event listener code is not executed](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed)

Closing since you didn't fill out the template. #1337 
You can join our discord server at https://discord.gg/jda or open a discussion.
