### ISSUE TITLE
Is there a wiki page for selection menus?

### ISSUE THREAD

**Issue by HippoBaguette** [DV8FromTheWorld/JDA#1728]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

https://github.com/DV8FromTheWorld/JDA/wiki/Interactions it says "Selection menus (coming soon)". Does it mean selection menus are going to be in a release soon, or there will be page about it coming soon? Or is the interactions oage just outdated?

**Comment by MinnDevelopment** [comment]
Selection menus are already available in the current development build: [Documentation](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.html)
They will likely not receive their own wiki page since they work essentially the same as buttons. You just get a `SelectionMenuEvent#getValues` in addition to the other methods that buttons also have, and they are created with a builder through `SelectionMenu.create("my_id")`.
