### ISSUE TITLE
Add an option to have JDA use a specific IP and Port

### ISSUE THREAD

**Issue by bigfinfrank** [DV8FromTheWorld/JDA#1740]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

A configurable option to choose a specific IP and port combination for JDA to use.

### Example Use-Case

- This is essentially required to use JDA in situations where the host server is configured to use a default-deny firewall setup (from my understanding/experimenting it's impossible to use JDA under these conditions as-is).

- Another example of where this would be useful is when running multiple bots off the same server- having each bot bind to it's own IP would avoid Cloudflare ratelimits for too many connection attempts after a server reboot. Plus it would mean that if one bot on the server was malfunctioning and the IP was blocked by Cloudflare it wouldn't affect the other completely unrelated bots that are functioning normally.

**Comment by MinnDevelopment** [comment]
You can configure the HTTP and WebSocket to change the [SocketFactory](https://docs.oracle.com/javase/8/docs/api/javax/net/SocketFactory.html) and [SSLSocketFactory](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocketFactory.html) and [bind](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#bind-java.net.SocketAddress-) them to specific addresses.

See:
- [JDABuilder#setWebSocketFactory](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setWebsocketFactory(com.neovisionaries.ws.client.WebSocketFactory)) and [WebSocketFactory#setSocketFactory](https://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html#setSocketFactory-javax.net.SocketFactory-)/[setSSLSocketFactory](https://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html#setSSLSocketFactory-javax.net.ssl.SSLSocketFactory-)
- [JDABuilder#setHttpClientBuilder](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setHttpClientBuilder(okhttp3.OkHttpClient.Builder)) and [OkHttpClient.Builder#socketFactory](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#socketFactory-javax.net.SocketFactory-)/[sslSocketFactory](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-javax.net.ssl.X509TrustManager-)

Since JDA only communicates through these libraries, I don't see how we can do much more here. Feel free to let me know!
