### ISSUE TITLE
What is the proper way to get the message from a GuildMessageReactionAddEvent?

### ISSUE THREAD

**Issue by MillzyDev** [DV8FromTheWorld/JDA#1966]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

I'm trying to retrieve the message from a `GuildMessageReactionAddEvent`, my current setup produces a `NullPointerException` and i am at point where I am unsure of what to do. My current setup is in the "Example Code" section. Is there an intended way to do this?

## Example Code

```java
    @Override
    public void onGuildMessageReactionAdd(@Nonnull GuildMessageReactionAddEvent event) {
        Message message = event.getChannel().getHistory().getMessageById(event.getReaction().getMessageId());
        // message is null
    }
```

**Comment by Xirado** [comment]
You need to retrieve the message using `Channel#retrieveMessageById`

**Comment by MillzyDev** [comment]
Thank you for the speedy reply! That worked, thank you for the help!

**Comment by DManstrator** [comment]
@MillzyDev You could use [`GenericGuildMessageReactionEvent#retrieveMessage`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/message/guild/react/GenericGuildMessageReactionEvent.html#retrieveMessage()) instead which was added back then as a convinience method (which will do the exact same).

Note that using the [`MessageHistory`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/MessageHistory.html) for getting messages will not work in 99% of all cases, since JDA doesn't cache Messages. It will just contain messages you retrieved via. the MessgeHistory, eg. using `retrievePast`, `retrieveFuture`, etc.

If you are not in a such event, use what Xirado told you.

cc @Xirado
