### ISSUE TITLE
Receive Audio

### ISSUE THREAD

**Issue by GigaDroid** [DV8FromTheWorld/JDA#21]
I got sending audio working, but what I need is to receive audio.
I understand that I need to create an `AudioReceiveHandler` and play sound from the `AudioPacket` provided in the `handleReceivedAudio` function.
The problem is how do I play the audio from the byte array?
Hope someone can help me

**Comment by DV8FromTheWorld** [comment]
I have put my focus on Sending audio to begin with. Sending will be out with v1.3.0.
Receiving audio will be out with v1.4.0, Currently, you receive an AudioPacket in handleReceivedAudio. This is an represention of the literal raw packet received. You would need to use an opus decoder to decode the getEncodedAudio in the packet. You would also need a different decoded for each SSRC that is in the VoiceChannel. Lastly, after decoding, you would need to mix the decoded bytes together, based on their timestamps so that you can have 1 complete audio stream.

I would seriously suggest waiting until I provide a simple API for this. Currently it is "here is the raw stuff".

Sorry :/

**Comment by DV8FromTheWorld** [comment]
This is finally.. FINALLY being worked on.
This will be released in JDA v2.2.0.
You can follow the progress on the `audio_receiving` branch.

Currently, User specific audio is supported. Combined audio is coming soon.

**Comment by DV8FromTheWorld** [comment]
As of PR #85, This has finally been finished!
Look for it in version 2.2.0!
