### ISSUE TITLE
AudioManager#openAudioConnection() silently fails sometimes

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#212]
I was getting a report that one of my shards were unable to join voice channels. I went ahead and tested this shard on another server, but it would repeatedly silently fail to join a voice channel. The same code works fine on other shards.
Code used:
```java
AudioManager manager = guild.getAudioManager();
manager.openAudioConnection(targetChannel);
```

Restarting the shard seems to temporarily have fixed the issue. I haven't logged any debug info from JDA.

I am running on c97947157a

**Comment by DV8FromTheWorld** [comment]
You say silently fail, but are you positive that you weren't being WebSocket ratelimited?

**Comment by Frederikam** [comment]
I didn't see anything in the log about being rate limited in any form. Besides, wouldn't that be affecting all shards if that was the case?

**Comment by DV8FromTheWorld** [comment]
No. Websocket sharding is shard specific because it is websocket connection specific. 120 packets per 60 seconds. Starting an audio connection, moving to a different channel, changing selfMute/selfDeaf, or closing a connection all involve sending a packet over the MainWS. When the socket is ratelimited, these packets are queued and sent after the 60 seconds is over.

**Comment by DV8FromTheWorld** [comment]
@Frederikam have you see this happen anymore?

**Comment by DV8FromTheWorld** [comment]
Going to assume that this is not an issue. Reopen if you encounter the issue again.
