### ISSUE TITLE
allowedMentions method in SlashCommandInteractionEvent does not work for roles

### ISSUE THREAD

**Issue by BlastyTheDev** [DV8FromTheWorld/JDA#2125]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Using the allowedMentions method, the reply to the SlashCommandInteractionEvent should have mentioned a role
Instead, the bot's message has the role mention in it, but didnt ping the role
![image](https://user-images.githubusercontent.com/79897422/167275043-cd7ba41e-0277-4465-a77a-9f33cef88141.png)
(i did have the role applied to myself)
(the image was the bot's reply)

### Code Example for Reproduction Steps

```java
@Override
public void onSlashCommandInteraction(@NotNull SlashCommandInteractionEvent e) {
    // I did have my role id filled in
    e.reply("<@&ROLE_ID>).allowedMentions(Collection.singleton(Message.MentionType.ROLE)).queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault("token")
        .setActivity(Activity.watching("activity")
        .addEventListeners(/*my listeners are here*/)
        .build().awaitReady();
```

### Exception or Error

```yesyes
N/A
```

**Comment by BlastyTheDev** [comment]
Note: User mentions using allowedMentions() did work.

**Comment by MinnDevelopment** [comment]
Is the role mentionable? Does the everyone role have mention everyone permission in the channel?

**Comment by BlastyTheDev** [comment]
My bot has administrator permissions

**Comment by MinnDevelopment** [comment]
The permissions of the bot are irrelevant for slash command replies. Please answer my questions.

**Comment by MinnDevelopment** [comment]
I just tested role mentions and they work fine if either of these conditions hold:

- The role is marked as mentionable

![image](https://user-images.githubusercontent.com/18090140/167292334-6cec9d0d-9c19-4938-a0b6-2bc16ce0390b.png)

- The **everyone role** has permissions to mention everyone in the channel

![image](https://user-images.githubusercontent.com/18090140/167292325-714ffad6-4870-4616-8839-676a9265263e.png)

Slash command replies do not make use of bot permissions due to the way discord designed them. These replies only make use of the permissions given to the everyone role at this time.
