### ISSUE TITLE
RateLimiter too slow!

### ISSUE THREAD

**Issue by MinusKube** [DV8FromTheWorld/JDA#222]
The Rate Limiter for the JDA Requests is "too slow", example with reactions:

When I add 20 reactions using Message.addReaction(), it takes about 10-15 seconds to put all the reactions, but when I make the requests using Unirest directly "Unirest.put(...)...", it only takes 3-4 seconds.

**Comment by MinnDevelopment** [comment]
This is due to a discord issue: [#182](https://github.com/hammerandchisel/discord-api-docs/issues/182)
The rate limit headers use a 1/1s limitation.
The actual limit is 1/250ms but discord doesn't provide a correct value in the header.

**Comment by MinusKube** [comment]
Yeah but maybe you can make an exception just for this endpoint? That would be nice to be able to make fast reactions without having to make requests using directly Unirest 😃

**Comment by DV8FromTheWorld** [comment]
This is a topic that has been discussed internally and will most likely come to fruition, however it isn't the primary focus. I am currently focused on doing project wide documentation.

Due to this technically not being a JDA bug but a discord bug, and it being known, I am closing this.
Look forward to something in the future.
