### ISSUE TITLE
GuildAvailableEvent down ?

### ISSUE THREAD

**Issue by Akio08** [DV8FromTheWorld/JDA#235]
Hello,

There is my code

GuildAvailableListener.java
```java
public class GuildAvailableListener extends ListenerAdapter {
    @Override
    public void onGuildAvailable(GuildAvailableEvent event) {
        System.out.print("[GuildListener] Available");
    }
}
```

Main.java
```java
// Code here
this.myBot = new JDABuilder(AccountType.BOT).setToken(key).addListener(this).buildBlocking();
this.myBot.addEventListener(new MessageListener(this));
this.myBot.addEventListener(new GuildAvailableListener());
// And more code here too
@Override
    public void onEvent(Event event)
    {
        if(event instanceof GuildAvailableEvent){
            System.out.print("[GuildListener] Available");
        }
    } 
```

And "[GuildListener] Available" is never printed....
The others event are working.

Hoping for help :(

**Comment by DV8FromTheWorld** [comment]
GuildAvailable only fires if, after JDA fires ReadyEvent, some of the Guilds aren't already available. This only occurs if Discord is having load issues so some Guilds are unavailable after full load. In a normal situation, Guilds are already available and loaded when the ReadyEvent is dispatched, thus you would not get GuildAvailableEvents.

In the case that a Guild is unavailable after Ready, when JDA receives Guild information from Discord marking the Guild available again, a GuildAvailableEvent would then be fire. Additionally, if JDA is already loaded and Discord informs us that a Guild suddenly becomes unavailable due to load or server downage a GuildUnavailableEvent would be fired.
