### ISSUE TITLE
Add another method for author for author name and icon only

### ISSUE THREAD

**Issue by CerialPvP** [DV8FromTheWorld/JDA#2355]
### General Troubleshooting

- [x] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

As said in the title, add another method for only the author name and author icon URL.
There are 3 methods, but none of them have the author name and URL only.
There might be another way to accomplish this that I don't know about, but for the sake of convenience add it. 

### Example Use-Case

```java
public void example(){
    // Make an embed builder
    EmbedBuilder builder = new EmbedBuilder()
        .addAuthor("Author Name", "Author Icon URL");
    // Send the embed
    getBot().getGuildById("ID_HERE").getTextChannelByID("ID_HERE").sendMessageEmbeds(builder.build());
}
```

**Comment by freya022** [comment]
`addAuthor` would imply you can show multiple authors, which you cannot, so it would be named `setAuthor`, for which an overload with two `String` parameters already exist, even though it sets the name and the url, instead of the icon url. It is not possible to add the method you requested.

You can however use [this overload](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/EmbedBuilder.html#setAuthor(java.lang.String,java.lang.String,java.lang.String)) and put `null` where necessary

**Comment by CerialPvP** [comment]
mb, also yes i just discovered that moments after posting this, ill close it
