### ISSUE TITLE
Throw exception when no intents

### ISSUE THREAD

**Issue by boomerboss** [DV8FromTheWorld/JDA#2411]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

When performing an action that requires intents that are not on, have JDA throw an exception describing the missing intents in the Dev portal.

### Example Use-Case

```java
public void onMessageReceived(@NotNull MessageReceivedEvent event) {
        if (!Bot.artChannels.contains(event.getChannel().getIdLong())) return;
        if (event.getMessage().getAttachments().isEmpty()) return; // without message content intent this is always empty, even when there are attachments in the message.
}
```

**Comment by MinnDevelopment** [comment]
We already [print a warning](https://jda.wiki/using-jda/troubleshooting/#cannot-get-message-content-attempting-to-access-message-content-without-gatewayintent). Throwing an exception is not possible, since we cannot be sure that the message is affected by the intent. In certain context's the message content intent does not apply, such as when the bot is mentioned, in direct messages, or in interactions.
