### ISSUE TITLE
GuildMemberUpdateNicknameEvent doesn't fire for the first nickname change after startup

### ISSUE THREAD

**Issue by LaserSlime** [DV8FromTheWorld/JDA#2467]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA should fire GuildMemberUpdateNicknameEvent for every nickname change to be able to monitor nicknames reliably. Instead it ignores the first change and then only fires for the next ones. 

### Code Example for Reproduction Steps

```java
@Override
	public void onGuildMemberUpdateNickname(GuildMemberUpdateNicknameEvent e) {
		System.out.println(e.getNewNickname());
	}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createDefault("token").enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.MESSAGE_CONTENT).setMemberCachePolicy(MemberCachePolicy.ALL).build();
```

**Comment by MinnDevelopment** [comment]
This is expected behavior, we can't see the update until the member is cached. You can preload members using [Member Chunking](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/JDABuilder.html#setChunkingFilter(net.dv8tion.jda.api.utils.ChunkingFilter)), or use the [GuildMemberUpdateEvent](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateEvent.html) instead.
