### ISSUE TITLE
onReconnect() does not trigger

### ISSUE THREAD

**Issue by xunkar** [DV8FromTheWorld/JDA#322]
I have setup my bot with the following listener

    @Override
    public void onReady(ReadyEvent event) {
       LOG.info("Connected to Discord");
    }

    @Override
    public void onDisconnect(DisconnectEvent event) {
       CloseCode code = event.getCloseCode();
       String reason = (code == null) ? null : code.getMeaning();
       LOG.info("Disconnected from Discord, reason: {}", reason);
    }

    @Override
    public void onReconnect(ReconnectedEvent event) {
       LOG.info("Successfully reconnected to Discord");
    }

While `onReady` and `onDisconnect` are properly triggered `onReconnect` is never called despite the bot managing to reconnect to Discord immediately after a disconnect event has been thrown. The JDA instance is set to automatically reconnect.

**Comment by DV8FromTheWorld** [comment]
`onResume` is called if a full reconnect is not needed. Resume and Reconnect both imply that the connection has been restored. Resume means it was done within a small enough time frame that the internal cache did not need to be invalidated, and it is a cheap reconnection. Reconnect means that discord requested cache invalidation due to being disconnected for too long. In this case, all JDA entities are destroyed and rebuilt upon reconnecting to discord.

Thus, Resume vs Reconnect.
