### ISSUE TITLE
Add TextChannel#isNSFW()

### ISSUE THREAD

**Issue by ShanerX** [DV8FromTheWorld/JDA#333]
If you're not aware, [Discord recently added the NSFW-channels feature](https://blog.discordapp.com/safety-boost-part-two-7b9069428437): TextChannels which are supposed to contain "18+" content should be set as NSFW to warn children.

Thus, I'm suggesting to add support for the NSFW feature in JDA (enabling/disabling).

**Comment by aurieh** [comment]
It's just prefixing the channel with `nfsw-` (or naming it `nsfw`). No flags, nothing special. Don't think it matters as you can just change the name.

**Comment by MinnDevelopment** [comment]
Yes we are aware of this new "feature". Since this isn't an api feature but a feature of the Discord Client which simply checks the name of a channel we didn't add it. If you really want this to be added feel free to open a Pull Request.
JDA is a wrapper for the discord api not a discord client backend.

**Comment by ShanerX** [comment]
@MinnDevelopment someone beat me to it. Thanks anyway.
