### ISSUE TITLE
JDA repeading every action endlessly

### ISSUE THREAD

**Issue by iAreas** [DV8FromTheWorld/JDA#420]
When i try to execue a command (such as send direct message ONE time), it will send 8 messages. This issue began in 3.2.0_XXX and is still a thing. It's very annoying, since i have to use outdated versions (3.1.0_XXX)

Code i use for sending direct messages is:

```
PrivateChannel dm = targetUser.openPrivateChannel().complete();
dm.sendMessage("Message content").queue();
dm.close();
```

**Comment by kijube** [comment]
Not sure, but is it possible that this happens due to you closing the `PrivateChannel `before the message was sent? You queued the Message Send Action, and then closed the channel. Maybe the message wasn't sent before you closed the channel as `queue()` doesn't block the current thread and `close()` gets called directly after it.

**Comment by iAreas** [comment]
@kijube It doesn't happen only with direct messages (i stated it just as an example), it also happens with regular chat messages in a guild.
And it's probably not because of me closing the channel because in older version (more specifically 3.1.0_204), it doesn't happen. Not with direct messages nor with chat messages.

**Comment by ArsenArsen** [comment]
Closing a channel has nothing to do with sending messages.

**Comment by Almighty-Alpaca** [comment]
I really don't think this is a JDA problem. A common mistake is that your bot listens to it's own message or that you just have multiple instances of your bot running.

**Comment by kantenkugel** [comment]
or the event listener added multiple times

**Comment by ArsenArsen** [comment]
As you stated, it'll send messages 8 times, so you probably forgot to close those seven tabs down there in IntelliJ ;)

**Comment by iAreas** [comment]
For all of you saying that that isn't JDA's bug, i have one question:

Why is THE SAME program in THE SAME environment working just great in JDA 3.1.0_204, but having that issue since JDA 3.2.0_226??

Also, i checked all methods and none is deprecated/missing.

**Comment by kantenkugel** [comment]
When exactly are you writing out that message? on what event?

**Comment by kantenkugel** [comment]
The thing is: 205 (the first build that breaks for you i guess) is pretty old (may 24th). And the fact that we didn't hear anything like this since then (with a huge user base) strongly suggests that its not JDA's error. 
That's why we first went with the "Its probably a user error" response first. 

We are still trying to help you fix this. We just wanted to make sure that its not your code producing this. (which I am still not sure about)

Could you find out on which exact build your program starts to act like this? Is it 205 or is it later? That would help enormously in finding out what causes that (looking at what changed in JDAin that version)

**Comment by MinnDevelopment** [comment]
You are not actually closing the channel in that example as close() is returning a ResAction. I don't believe this a JDA error and advise you to check and debug your code first. Closing a channel does not make a real difference for bots FYI.

**Comment by iAreas** [comment]
@kantenkugel As far as the downloads go, last build without that issue was 3.1.0_204, it began behaving so in 3.2.0_226, still behaves so in the latest build (3.2.0_241). Hope that helps.

And if you really want to make sure it's not my code, you can check it out [there](https://www.mediafire.com/file/62p23coadhgei8k/LiBotCode.zip).

(I'm new to Git stuff, and still don't know how to use it pretty much, so I'm just giving you the mediafire link)

**Comment by iAreas** [comment]
@MinnDevelopment i know that closing private channels doesn't make a big diffierence, but i still do it. And also I'm sure that doesn't cause the user to recieve 8 private messages when they should recieve only one FIY.

**Comment by Almighty-Alpaca** [comment]
@iAreas in which class is the affected code?

**Comment by iAreas** [comment]
@Almighty-Alpaca in every class that sends private/public messages.

**Comment by iAreas** [comment]
You guys should also stop bothering about the private message code and start bothering about the issue. I don't open issues if I'm not 100% sure that it's not my fault.

**Comment by MinnDevelopment** [comment]
As far as i am aware there is no issue in JDA that could cause this. Unless you can find and prove it I am certain this is your issue which is why i told you to debug.

**Comment by iAreas** [comment]
After reinstalling JVM & Eclipse, the issue disappeared. Kinda weird.

But at least it wasn't mistake in my code.

**Comment by SparklingComet** [comment]
> After reinstalling JVM & Eclipse, the issue disappeared. Kinda weird.
But at least it wasn't mistake in my code.

I thought this was the issue when I first read about your problem as it happened to me too, but I was unsure and preferred not to respond. It is likely that you had more than one running instances of your bot because you hadn't closed the previous ones properly.(all were listening and respoinding to events.)

**Comment by TotoAJ** [comment]
I had the same issue but I had to close and reopen eclipse because I had some java processes running in the background of eclipse.

**Comment by Tais993** [comment]
_2017_
