### ISSUE TITLE
Wondering how to send a user a message on first join.

### ISSUE THREAD

**Issue by Tropical-MC** [DV8FromTheWorld/JDA#545]
Sorry for asking this here but I don't know where to go, I'm trying to send a message to a user on join and this is all I can come up with. I cant find any docs on it.
```java
package me.mcsv.discord;

import net.dv8tion.jda.core.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.core.hooks.ListenerAdapter;

public class JoinListener extends ListenerAdapter {

	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event) {
		event.getMember().getUser().openPrivateChannel().queue();
	}
	
	
}
```

**Comment by MinnDevelopment** [comment]
User#openPrivateChannel() returns a `RestAction<PrivateChannel>` which provides the channel in the success callback.
Please read the wiki page for using rest actions https://github.com/DV8FromTheWorld/JDA/wiki/7)-Using-RestAction

If you have more questions like this please join our discord server instead of opening issues.
