### ISSUE TITLE
Error at initialization : permission_override

### ISSUE THREAD

**Issue by KaluNight** [DV8FromTheWorld/JDA#566]
## General Troubleshooting

Hey! When i try to intialize a JDA object, i get this error : 
`java.lang.RuntimeException: Got permission_override for unknown channel with id: 361465678508851200`
What does it mean ?
Info : I give all permission to the bot.

## Template
My code : 
```java
JDABuilder builder = new JDABuilder(AccountType.BOT);
builder.setToken("Token");
builder.setAutoReconnect(true);
builder.setStatus(OnlineStatus.ONLINE);
```

**Comment by MinnDevelopment** [comment]
Have you tested this code on the latest version of JDA?

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help. If the issue is then found to be a bug you are free to open an issue with the needed information.
