### ISSUE TITLE
MessageUpdateEvent not firing

### ISSUE THREAD

**Issue by TommyChums** [DV8FromTheWorld/JDA#570]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

> This is not the place to learn Java. Please refer to [StackOverflow][stack overflow]
  for your general programming questions.

### Issue Type
- [ ] Bug Report
- [ ] Feature Request

### Description

The MessageUpdateEvent never seems to fire when a message is edited in either a private channel or textchannel

**Comment by Sanduhr32** [comment]
ATM there was a Discord issue. Please test it later again.

**Comment by MinnDevelopment** [comment]
Cannot reproduce that behaviour.

**Comment by TommyChums** [comment]
Still does not work for me and has not been working for the past week or so

**Comment by MinnDevelopment** [comment]
This sounds like you have not set your event handling up properly. Please join our discord server to receive help.
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by TommyChums** [comment]
Alright thank you
