### ISSUE TITLE
JDALogger does not correctly detect presence of a SLF4J Implementation provider, starting from SLF4J 1.8

### ISSUE THREAD

**Issue by Enveed** [DV8FromTheWorld/JDA#580]
### Issue Type

- [X] Bug Report
- [ ] Feature Request

### Description

Starting from SLF4J version 1.8, the old `org.slf4j.impl.StaticLoggerBinder` method of providing an implementation for SLF4J is no longer working, as detailed here: https://www.slf4j.org/codes.html#noProviders

The new way to provide an implementation is via `SLF4JServiceProvider` and a [*service-provider configuration* file](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html).

This would not be a problem if JDA would be entirely based on the exposed side of SLF4J's API, but [`JDALogger`](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/utils/JDALogger.java) does an additional check for the presence of the old `StaticLoggerBinder`, [here](https://github.com/DV8FromTheWorld/JDA/blob/e8374137764a09733b1be9f56a7654af85788edd/src/main/java/net/dv8tion/jda/core/utils/JDALogger.java#L46) and uses a `SimpleLogger` instead of the SLF4J provided Logger if the class is not found:

```Java
public static final boolean SLF4J_ENABLED;
    static
    {
        boolean tmp = false;
        try
        {
            Class.forName("org.slf4j.impl.StaticLoggerBinder");
            tmp = true;
        }
        catch (ClassNotFoundException e)
        {
            //prints warning of missing implementation
            LoggerFactory.getLogger(JDALogger.class);
        }
        SLF4J_ENABLED = tmp;
    }
```

This obviously fails starting from 1.8 since implementation providers do not include this class anymore, but instead a `SLF4JServiceProvider`.

This logic has to be fixed to work with SLF4J 1.8+.

I know JDA is currently using SLF4J [`1.7.25`](https://github.com/DV8FromTheWorld/JDA/blob/e8374137764a09733b1be9f56a7654af85788edd/build.gradle#L56), however, this is probably important for the future.

### Temporary solution

This may be useful for other people who want to use SLF4J 1.8 instead of the version provided by JDA in their project for some reason, until this is fixed. Note: **This is VERY EVIL, NOT recommended  and in no way guaranteed to work in your situation!** (It does for me tho)

```Java
    /**
     * Do some evil stuff to get JDA to use an existing SLF4J implementation instead of SimpleLogger, if present
     * @throws Exception if something goes wrong
     */
    private void setUpJDALogger() throws Exception {

        if(Lists.newArrayList(ServiceLoader.load(SLF4JServiceProvider.class)).isEmpty()) return; // no service providers

        Field field = JDALogger.class.getDeclaredField("SLF4J_ENABLED");

        field.setAccessible(true);

        Field modifiersField = Field.class.getDeclaredField("modifiers");
        modifiersField.setAccessible(true);
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);

        field.set(null, true);
    }
```
([source for the final field modification](https://stackoverflow.com/questions/3301635/change-private-static-final-field-using-java-reflection))

### Example for a final solution

I did not test if this is fast or causes any problems, however, this should work:

```Java
public static final boolean SLF4J_ENABLED;
    static
    {
        boolean providerAvailable = 
        !Lists.newArrayList(ServiceLoader.load(SLF4JServiceProvider.class)).isEmpty();
        
        if (!providerAvailable)
        {
            //prints warning of missing implementation
            LoggerFactory.getLogger(JDALogger.class);
        }
        SLF4J_ENABLED = providerAvailable;
    }

```

**Comment by kantenkugel** [comment]
This kinda seems like a 2-edged sword as [the slf4j faq](https://www.slf4j.org/faq.html#changesInVersion18) mentions that slf4j-api v 1.8 is not compatible with earlier providers (not backwards compatible) **and** using slf4j-api v 1.7 or earlier doesn't support the new providers, as the providers don't have the static binding class anymore.

So its best to keep it in JDA as-is until we update to slf4j-api 1.8, as 1.8 providers won't work with the currently used slf4j-api version anyway.

And seing as this is the first report for not being compatible with 1.8, i guess that most users still use the 1.7 providers, therefore its best to stay with 1.7 api version as well for the time being

**Comment by MinnDevelopment** [comment]
As @kantenkugel mentioned, it seems like SLF4J 1.8 is not compatible with later versions. From my understanding a binding for both 1.7.X and 1.8.X have to be present if using incompatible api versions.
JDA will not be moving away from 1.7.X as it is the stable release and most spread release. I don't know if there is a good way to allow compatibility with both versions but if that is not the case we can't do anything about it.

**Comment by MinnDevelopment** [comment]
This issue seems to be stale.

**Comment by enveeed** [comment]
Sorry for commenting on this issue once again after all this time, but i've been working with Discord and JDA once again and came back to this problem.

The problem is actually not that JDA will stay with `1.7.x` while users of it use `1.8.x`, but the fact that JDA does not just depend on SLF4J itself to detect if it has a binding or not. If this would not be the case,
using `1.8.x` bindings with a `1.7.x` API would be no problem at all, because if a `1.8.x` version of API is provided at runtime, which is binary compatible with `1.7.x`, everything would work correctly.

Currently this is only possible to achieve by using the method above to set `SLF4J_ENABLED` to true despite the JDA mechanism not finding a binding, and pretending SLF4J has a binding, which is actually the case, just JDA can't detect it because its binding detection only works with `1.7.x`.
This way includes modifying a final field which is only possible by editing `reflect.Field` internal fields and because of that causes warnings about illegal reflective access in JDK9+.

It still works in JDK11 but according to the warning, illegal reflective access may be completely disallowed in the future, which would make it impossible to solve this issue.

Because of this, I propose to modify `JDALogger` and remove its binding detection mechanism and to rely entirely on SLF4J itself for this, which would provide maximum compatibility with all SLF4J versions and also finally completely solve this issue.

I may make a pull request when I get the time, if this proposal sounds alright to the dev team.
