### ISSUE TITLE
Delete emotes

### ISSUE THREAD

**Issue by KingFaris10** [DV8FromTheWorld/JDA#583]
## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

Hi, I've made a 'create emote' command for my bot. However users have requested a 'delete emote' command. I noticed a createEmote method in GuildController, but there doesn't seem to be a delete emote method. I was wondering if this was possible, and if so, could it be implemented, thanks.

**Comment by MinnDevelopment** [comment]
[Emote#delete()](http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/entities/Emote.html#delete--)

Please ask in the discord server first next time.

**Comment by KingFaris10** [comment]
My bad, I expected the API to have made more sense in that 'delete()' method shouldn't exist in the Emote class but rather in the GuildController class named 'deleteEmote'. Thanks anyway, and will do in the future.

**Comment by MinnDevelopment** [comment]
If there was `GuildController#deleteEmote(Emote)` you would have to get both a GuildController and the Emote itself to delete it. 
```java
guild.getController().deleteEmote(guild.getEmoteById(emoteId)).queue();
```
vs
```java
guild.getEmoteById(emoteId).delete().queue();
```

It makes no sense to have it that way considering all delete() methods are on the entities itself since you need the entity in order to even delete it in the first place.
The reason why createEmote falls out of place is that it cannot be on the Emote entity as it doesn't exist yet since you are just now creating it.

**Comment by KingFaris10** [comment]
I see your point.
