### ISSUE TITLE
.getAudioManager() isn't independent

### ISSUE THREAD

**Issue by TheMaskedMonkey** [DV8FromTheWorld/JDA#63]
I'm not sure if this is a design flaw or intended but when using the audio feature of the bot on multiple servers, it struggles to work out which is which. I'm able to control the music for 1 server from another. Is this intended?

**Comment by DinosParkour** [comment]
Are you using the latest version's `Guild#getAudioManager` or maybe an older version that doesn't support multi-voice with `JDA#getAudioManager`? I haven't had any issues with AMs like that.

**Comment by TheMaskedMonkey** [comment]
I'm using this version: https://github.com/DV8FromTheWorld/JDA/releases/tag/v2.0.0

and this to send audio:

```        			//audioFile = new File("test.m4a");
        			audioUrl = new URL("http://url.here/");
        			player = new URLPlayer(event.getJDA(), audioUrl);
        			
        			event.getGuild().getAudioManager().setSendingHandler(player);
        			
        			player.play();```

**Comment by DinosParkour** [comment]
In theory, if you can retrieve the guild you want to control then you will be able to do whatever you want with it regardless of the guild which the message was sent in (assuming that it's all managed through a command).

However, the snippet you included specifically gets the current Guild's AudioManager, so I don't see how that would fail and use another guild's AM.. Is the rest of your code open source so we can take a look at it? Also, could you join either the [Discord API guild](https://discord.gg/0SBTUU1wZTYFGm6s) or [JDA's Guild](https://discord.gg/0hMr4ce0tIjwX37L) in order to communicate more efficiently? Thanks.

**Comment by TheMaskedMonkey** [comment]
I joined the JDA guild :) I'm TheEpTic :D

**Comment by TheMaskedMonkey** [comment]
Resolved thanks to @DinosParkour
