### ISSUE TITLE
MessageHistory always empyty

### ISSUE THREAD

**Issue by ThibautCuchet** [DV8FromTheWorld/JDA#657]
Hi,
I try to use MessageHistory to get a list of last message send in a channel.
But when I check the size of the history (.size() ) , the function return always 0, I tried to use this on differents channel but nothing changes.

Can you help me ?

**Comment by WalshyDev** [comment]
`Creates a new MessageHistory object for each call of this method. 
MessageHistory is NOT an internal message cache, but rather it queries the Discord servers for previously sent messages.`

I assume you're running size on the wrong thing. It's a good idea to read the docs.

Also,
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.

**Comment by ThibautCuchet** [comment]
Thank you

**Comment by kantenkugel** [comment]
@ThibautCuchet can i assume this is resolved then? Please close the issue if so. Otherwise I will do so soon if there is no further response
