### ISSUE TITLE
[QUESTION] How to create instant invite and share link

### ISSUE THREAD

**Issue by Maxime6678** [DV8FromTheWorld/JDA#672]
Hello,

I want to create an invitation and share the link as a message. I am currently using the InviteAction class with the following code: InviteAction invite = event.getJDA().getGuildById(id).getDefaultChannel().createInvite();. But here I do not know how to get back the link: D

Thank you for your help

**Comment by Sanduhr32** [comment]
I suggest you joining the support guild because github issues are for feature or bug reports. Link is in the README.md of this repo

**Comment by MinnDevelopment** [comment]
`InviteAction` is a `RestAction`. Use the success callback [what?](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction#using-queue).

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
