### ISSUE TITLE
Javadocs don't load from the most recent release

### ISSUE THREAD

**Issue by Jedimaster4559** [DV8FromTheWorld/JDA#693]
[Page with Broken Link]: https://github.com/DV8FromTheWorld/JDA/releases/tag/v3.6.0
[Broken Link]: http://home.dv8tion.net:8080/job/JDA/javadoc

## Issue
On the above page, the link to the documentation for JDA is broken and will not load.

### Issue Type
- [ ] Broken Link

### Description
The link to the documentation seems to be broken. The link itself will not load for me. This was brought to my attention by viewers on my youtube channel who were having a similar issue.

**Comment by averen** [comment]
This is because the server is not available. The backup docs are [here](https://www.kantenkugel.com/jdadocs).

Furthermore, the github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.

**Comment by Sanduhr32** [comment]
Hello jedimaster, we are aware of that issue and we know how we can help you.

Sadly the github issue tracker is mainly used for bug reports and feature requests. Would you mind joining the support guild by using the README.md s invite when you have another issue? https://www.kantenkugel.com/jdadocs or the second pin in the general chat.

**Comment by kantenkugel** [comment]
Just a note: as our main docs are back up, i removed the backup docs from my own server. The index file now links back to the proper docs from Jenkins [here](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/javadoc/)
