### ISSUE TITLE
Get Member or Guild from User

### ISSUE THREAD

**Issue by AndrewShorty** [DV8FromTheWorld/JDA#712]
How can i get Member/Guild from a User for a Mute/Ban System?!

**Comment by kantenkugel** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

In your case, Take a look at the docs available online [HERE](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/javadoc/)
