### ISSUE TITLE
RestAction should implement Publisher

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#715]
### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description
I have been using [Project Reactor](https://projectreactor.io/) for a few months now. Libraries like these make it easy to work with async operations in a functional way. Lately, I figured that JDA's `RestAction` can be adapted to fit into this API by implementing `Publisher`.

A Publisher's action will only start once it has been subscribed to (similar to rest actions). Multiple subscribers may be added. Subscribers are like event handlers, and handle these 4 events:

- `onSubscribe(Subscription)`
- `onNext(T)`
- `onError(Throwable)`
- `onComplete()`

The problem with this is that the flow API was introduced in Java 9. I am not sure if the JVM allows us to implement an interface which is not loaded (say when running JRE 8).

Documentation:
- https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/Flow.Publisher.html
- https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/Flow.Subscriber.html
- https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/Flow.Subscription.html

**Comment by kantenkugel** [comment]
As we are building against java8, this will probably not work then.

And we will very likely stay on 8 for a while (compatibility) and then sometime in the future switch to Java 11. At that point we can consider adding the stuff described in the issue, but currently it won't work i guess.

**Comment by MinnDevelopment** [comment]
We currently have no plans on using any features from java 9 or beyond.

**Comment by DV8FromTheWorld** [comment]
Since we are planning to stay on `Java 8` for the foreseeable future, this should probably be closed

**Comment by napstr** [comment]
When you are saying "no plans for java 9 or beyond" and "forseeable future", do you plan on staying on Java 8 despite the next LTS release coming out in about 2 months, and beyond Java 8 stopping getting public updates in January 2019 which is just 6 months from now?

**Comment by MinnDevelopment** [comment]
Yes, we don't want to force our users to upgrade their java version because someone wants some feature of it implemented in JDA.

**Comment by napstr** [comment]
Noone is forced to update anything. Users who use Java beyond its public support time can just use the last JDA java 8 version. Why would they mind using an old JDA version when running on an outdated and possibly insecure JVM?
Or maybe those users (whose existence is very questionable in the first place) can contribute their own java-8 backport branch of JDA, instead of holding off everyone else from going with the time?

**Comment by MinnDevelopment** [comment]
Java 8 will continue getting extended support until 2025, how is that possibly insecure or outdated? The majority of the industry will stick to java 8 for years to come. Nobody has interest in developing 2 versions when using java 8 is completely fine for us/them, java 9/10/11 do not bring enough for us to consider this change.

**Comment by napstr** [comment]
Yes, if you are a paying customer of Oracle, then you will receive Oracle JDK 8 updates till 2025. For everyone else this ends at January 2019.
The **only** other public and free alternative I have found is https://adoptopenjdk.net/support.html who commit to supporting jdk8 builds till 2022.
"the majority of the industry" is going to have to pay Oracle for updates or take the risk of incompatibilities by switching vendors. Or do the sane thing and update.

@kantenkugel The solution to that would be the java8 backport branch/fork that I suggested. Anyone insane enough planning to stay on Java 8 should be putting in the work to stay on outdated versions.

**Comment by MinnDevelopment** [comment]
Then you're forcing work on the user by not continuing to update that release, so either way the library user gets the bad end of the stick. For... an interface? Seems out of proportions.

**Comment by napstr** [comment]
Sorry - it seems that I piggy backed this conversation on an issue that's only remotely related.
I don't have any pro or contra arguments regarding whether this specific feature itself is worth doing the version bump. I do think that it is worth having, but I fully understand making a decision **now** in favor of preserving compatibility for a longer time. Seeing that you we're not aware of the rather close end of life for the (oracle) jdk 8 you might want to adjust your internal road map. A suggestion would be to introduce some kind of `java 9+` label, so that all issues that were rejected due to having to bump the version can the found easily to make an assessment later whether bumping the version would seem more desirable.

**Comment by MinnDevelopment** [comment]
The reason we do not want to update is backward compatibility. Considering that we don't gain a lot of bumping the version while we bring an inconvenience to the userbase is a big influence on the decision that we want to stay java 8 compatible for now.
