### ISSUE TITLE
[Question] How to create channel?

### ISSUE THREAD

**Issue by defcorez** [DV8FromTheWorld/JDA#724]
Help me. How to create channel? What am I doing wrong?
`GuildAction guildAction = new GuildAction(event.getJDA(), event.getGuild().getName()); guildAction.addChannel(guildAction.newChannel(ChannelType.TEXT, "channel-name")).queue();`

When using I get this output:
`DEBUG net.dv8tion.jda.core.requests.Requester - Encountered issue with headers when updating a bucket`

What is the problem?

**Comment by MinnDevelopment** [comment]
The problem is that you are looking at DEBUG logs, its not a problem.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
