### ISSUE TITLE
OAuth2 email verification

### ISSUE THREAD

**Issue by gino21430** [DV8FromTheWorld/JDA#727]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x]  I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

> This is not the place to learn Java. Please refer to [StackOverflow][stack overflow]
  for your general programming questions.

### Issue Type

- [x] Feature Request

### Description

May you add a method "isVerified()" in user class?

In Disocrd Doc, user object can return with email with OAuth2

I want to distinguish email-verified user and non-verified to determine whether add him a role.  Thanks.

**Comment by averen** [comment]
The extra fields are only returned when viewing yourself, or using OAuth2. It is not possible to do this because in the OAuth2 process the user has to authorize your application from the browser. From the authorization, you get a code, which can be used to get a token. You would have to implement this yourself in your application.

**Comment by gino21430** [comment]
thanks a lot!
