### ISSUE TITLE
A function to get a message by its id

### ISSUE THREAD

**Issue by koflin** [DV8FromTheWorld/JDA#737]
### Issue Type

- [ ] Bug Report
- [x] Feature Request

> For questions join the official JDA discord server: https://discord.gg/0hMr4ce0tIl3SLv5

### Description

I would love to see a function added to the Guild class which can get a Message by its id without me looping through all TextChannels.

**Comment by natanbc** [comment]
[The discord API needs a channel ID to retrieve the message.](https://discordapp.com/developers/docs/resources/channel#get-channel-message)

**Comment by koflin** [comment]
Yeah this is why you would loop through all TextChannels. You already got a function for that.

**Comment by natanbc** [comment]
And do multiple useless requests?

**Comment by koflin** [comment]
Yes, there is no other option if you don't know the id of the channel. I just thought it would be useful.

**Comment by napstr** [comment]
>without **me** looping through all TextChannels.
>Yeah this is why **you** would loop through all TextChannels

?

Whether this is implemented in JDA or your own code, in both cases it is **your bot** looping through the channels and by doing so exhausting it's ratelimits, and possibly abusing the Discord API.

**Comment by kantenkugel** [comment]
This is a terrible feature to have imo.
You should store the channel id together with the message id if you want to look that message up later on.

Iterating over all (possibly thousands) of textchannels and doing a REST request for each of them is a terrible idea. Not only will it cap out your ratelimit pretty damn fast, but it would also run for half an eternity (due to ratelimit AND it being a lot of REST calls, each taking a few 10ms)

**Comment by koflin** [comment]
I got you. I will therefore additionally store the textchannel id.

**Comment by kantenkugel** [comment]
I gladly reject this feature request and strongly advice you to switch to a different method not requiring to iterating over all channels
