### ISSUE TITLE
Which ports does JDA use?

### ISSUE THREAD

**Issue by Jire** [DV8FromTheWorld/JDA#742]
Which ports and what type (TCP or UDP) does JDA use?

The API works great on my local computer but on a locked-down dedicated server it can't connect, which I'm assuming the firewall is blocking a port that JDA uses.

Thank you! 😸

**Comment by kantenkugel** [comment]
JDA isn't really using any listening ports so the firewall shouldn't really be a problem. The only ports we are listening to are audio receive ports and worst case you would just not receive audio.
Please join our support server for further questions.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
