### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wizardofwaverlyplace** [DV8FromTheWorld/JDA#760]
Is there some kind of documentation for JDA listing all the commands and what they do (such as https://discord.js.org/#/ but for this)

Sorry if this shouldn't be posted here, or there is documentation in an obvious spot. I looked around and I couldn't find anything so I didn't really know what else to do besides this.

**Comment by natanbc** [comment]
You can find the javadocs for the latest build in http://home.dv8tion.net:8080/job/JDA/javadoc/

**Comment by wizardofwaverlyplace** [comment]
Thank you, that is perfect!

**Comment by Almighty-Alpaca** [comment]
How about looking at the [github wiki](https://github.com/DV8FromTheWorld/JDA/wiki/8%29-List-of-Events) :eyes: 

Also the github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive further help.
