### ISSUE TITLE
Getting inputstream from the audio in a voice channel?

### ISSUE THREAD

**Issue by AutismSpeaks** [DV8FromTheWorld/JDA#87]
How would i go about getting an inputstream from the audio in a voice channel

**Comment by DV8FromTheWorld** [comment]
In JDA `3.0` I'm considering creating an implementation of AudioReceiveHandler that would allow you to retrieve an AudioInputStream. Be on the lookout for that when it comes out.

**Comment by Rokirok** [comment]
This was implemented in 8a104f365fbd9b71d5605712bdd6c9e8a3619ee0

**Comment by DV8FromTheWorld** [comment]
No it wasn't. This requests an implementation of AudioRecieveHandler that acts as an AudioInputStream. The commit you referenced does not provide that.

**Comment by Panzer1119** [comment]
Is this still a thing? And could someone show me how to build an AudioInputStream with the help of the AudioReceiveHandler?

**Comment by BenjaminUrquhart** [comment]
I am working on an InputStream wrapper for Channel object (including VoiceChannels).
If you want to try that, here: https://github.com/BenjaminUrquhart/CIS

**Comment by BenjaminUrquhart** [comment]
@AutismSpeaks 
I am working on an InputStream wrapper for Channel objects (including VoiceChannels).
If you want to try that, here: https://github.com/BenjaminUrquhart/CIS

**Comment by Trigary** [comment]
How would an `AudioInputStream` work? One can only create an `AudioInputStream` instance when its length (count of sample frames) is already known. This means that you can only store a fixed length of audio in an `AudioInputStream`, it can't be a real stream as in one that is going to receive new data constantly. It might still be useful to provide `AudioInputStream` instances though, it would just have to have a specified length and would need a handler that takes these instances. (Think about how some recording software works: they save multiple files of a fixed length. Each `AudioInputStream` here would represent a file.)

A normal `InputStream` might be more useful, but I am not familiar with what today's Java voice recognition, real-time processing libraries take as an input.

**Comment by SageSphinx63920** [comment]
Is it now possible to get an AduiInputStream?

**Comment by BenjaminUrquhart** [comment]
> Is it now possible to get an AduiInputStream?

Not that I know.

**Comment by DV8FromTheWorld** [comment]
This will likely never make its way into JDA because of what [AudioInputStream](https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioInputStream.html) _is_.
> An audio input stream is an input stream with a specified audio format and length.

Audio that flows out of VoiceChannel (via an [AudioReceiveHandler](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/audio/AudioReceiveHandler.html)) doesn't _have_ a specified length because it is real-time data.  [AudioInputStream](https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioInputStream.html) is meant to represent audio sources that are full-encapsulated like a file of song as an mp3. They have a known length.

As such, there's no real way to expose an [AudioInputStream](https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioInputStream.html) from JDA as AudioInputStream, as a construct, _does not_ support continuous data.

If you have another library that only accepts AudioInputStreams I would recommend you capture some finite amount of data using an  [AudioReceiveHandler](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/audio/AudioReceiveHandler.html) (thus you have a known length) and then construct an [AudioInputStream](https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioInputStream.html) from that captured data and pass it anywhere that needs an AudioInputStream.
