### ISSUE TITLE
Trojan detected on download

### ISSUE THREAD

**Issue by stefaandevylder** [DV8FromTheWorld/JDA#873]
Hello

When I try to download the docs windows says it contains a trojan.
https://gyazo.com/1e34dc0a7e9a59100ee9c86b309df2f7

Kind regards

**Comment by napstr** [comment]
Try scanning the file with brain.exe

**Comment by stefaandevylder** [comment]
> Try scanning the file with brain.exe

Thats a bit rude, I know it does not contain one but I'm just reporting it

**Comment by napstr** [comment]
You're reporting in the wrong place then, you should report the false positive to the security software of a questionable quality that you are using.

**Comment by stefaandevylder** [comment]
> You're reporting in the wrong place then, you should report the false positive to the security software of a questionable quality that you are using.

Alright, ill report it to windows since I'm not using one

**Comment by kantenkugel** [comment]
@stefaandevylder im guessing you got that from the Github release download?

We seem to randomly get those which are then fixed by just re-uploading from the CI server.
I don't know if this is a issue of github or idk...

Have you tried getting the build directly from jenkins? (should be linked from the readme and other sources)
