### ISSUE TITLE
Building Includes JNA Manifest Instead of My Own

### ISSUE THREAD

**Issue by xeu100** [DV8FromTheWorld/JDA#875]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

When compiling my JAR file, and I've tried many times with Maven and my IDE's (IntelliJ) built-in compiling software, it either doesn't build the dependencies or it builds with the JNA manifest instead of my own. I have attempted many fixes, including changing my .POM and build settings, however, nothing seems to resolve the issue.

**Comment by MinnDevelopment** [comment]
This is not an issue with JDA but your build method. You can ask in our discord server for help on setting up a proper build method, however this is not a JDA bug.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
