### ISSUE TITLE
JavaDoc not building on JitPack for v4

### ISSUE THREAD

**Issue by Vampire** [DV8FromTheWorld/JDA#923]
Building the JavaDoc on JitPack does not work for v4 as you can see at https://jitpack.io/com/github/DV8FromTheWorld/JDA/v4-v3.7.1-g67c88d3-174/build.log.
The problem is that you use `-html5` JavaDoc option but do not configure JitPack to build on Java 9+.
You can either do one of (or both)
- Configure newer Java in `jitpack.yml`, for example like
```
jdk:
  - openjdk10
```
- Make the `-html5` switch dependent on the version built with, for example like
```
if (JavaVersion.toVersion(toolChain.version).java9Compatible) {
    addBooleanOption 'html5', true
}
```

**Comment by MinnDevelopment** [comment]
1. We don't publish builds to JitPack
2. JDA 4 is available on jcenter

I see no point in trying to support every ci on the market by putting 20 config files into our repository just so that even the most edge-case CI can build our library.

I might look into making the html5 flag depend on the java version, but this can hardly be seen as a priority at this point.

In the meantime you can use:

- A slightly older build on [jitpack](https://javadoc.jitpack.io/com/github/DV8FromTheWorld/JDA/06765f9c8498f9e73d1018c6898f8c73debb81e2/javadoc/index.html)
- Download the javadoc jar from [jcenter](https://jcenter.bintray.com/net/dv8tion/JDA/4.ALPHA.0_34/:JDA-4.ALPHA.0_34-javadoc.jar)
- Clone the repository and build them yourself

**Comment by Vampire** [comment]
Ok, let me elaborate a slight bit so you understand my use-case and maybe you have a better solution.
I was not aware that you don't officially support JitPack as Kantenkugel specified the JitPack JavaDocs as fallback if the CI once again is down like currently, so I assumed it is expected to build fine.

Even if the CI were up, as far as I remember it only provides "latest" JavaDoc, not JavaDoc for multiple versions.
I'm building a library where I support JDA v3 and v4 and want my JavaDoc to link somewhere and not have ugly FQCNs in the generated docs.

For every lib I support that publishes to Maven Central (or JitPack actually) this is no problem, as javadoc.io automatically supports browsing JavaDoc for any version deployed to Maven Central without any further action needed, and the same for JitPack, as long as the build produces a JavaDoc artifact, it is browsable.

Unfortunately I didn't find any service doing what javadoc.io does for JCenter and the feature request to those guys to support it is untouched since a year and as far as I have seen you do not publish your JavaDocs anywhere else.

When I added support for v4 yesterday, I wanted to look at the CI server to see what JavaDocs are provided actually to find that the CI is once again down. As I've seen it down multiple times already and iirc only supports latest JavaDoc anyway, I searched again for an alternative and came to a quote of Kantenkugel in the DAPI server where he suggests JitPack as the fallback solution which would have worked out fine for me if it would have built.

Now that you made the flag dependent on the Java version (thanks) I can of course again link to JitPack, downloading the JAR from JCenter or building the JAR myself is of course not really helpful for my use-case. But do you have any other idea on how to properly solve this, assuming you are not considering to deploy to Maven Central?

**Comment by MinnDevelopment** [comment]
The host for our jenkins instance has changed about half a year ago and has been very reliable since then. It went down because an unexpected change that was supposed to be relayed to us caused the IP of the server to be changed. Since the domain is owned by @DV8FromTheWorld we are unable to update it currently for the new IP `144.172.70.54:81`. The server is up and running fine currently and hosts documentation for both v3 and v4 at the moment (this might change once v3 becomes discontinued).

You can access it through the port `81` without TLS since the nginx proxy only listens for the `ci.dv8tion.net` domain. We expect the domain to be updated soon, probably by tomorrow so the issue will be resolved by then.

I don't actively try to support JitPack versions, the backup quote was still relevant for v3 but not v4 which is currently not even supposed to be used. Besides that I don't believe JitPack to be a reliable source for javadocs which is why we host them on jenkins. You can always download the jars from jcenter and host them yourself as a backup if our server goes down. However, this does not happen often since we switched hosts to a more reliable provider.

Javadoc for [v4](http://144.172.70.54:81/job/JDA4-Alpha/javadoc) and [v3](http://144.172.70.54:81/job/JDA/javadoc) is currently available with the direct IP access.

**Comment by Vampire** [comment]
So cut short, you don't have any better idea and don't want to improve on that, but thanks for the status heads-up.

(
- Having a source that will not provide V3 docs in the future is not too nice, as my lib will still support v3 and it would be good if the links still work
- Using IP based URL is bad for the very same reason domain names exist and this downtime shows
- Downloading JARs and hosting them myself is bullshit and you know that, I just want to link from my documentation to your documentation reliably and not be a backup host for your server
)

May I ask why you think JitPack is not a good source for JavaDoc?
Actually I think JitPack is generally not the best invention, but it is at least nice if there is no other option.
javadoc.io is a great source for JavaDoc for all released versions, but for that as mentioned you would need to deploy to Maven Central (too).

**Comment by MinnDevelopment** [comment]
>Having a source that will not provide v3 docs in the future is not too nice, as my lib will still support v3 and it would be good if the links still work

We do not host documentation for unmaintained library versions.

>Using IP based URL is bad for the very same reason domain names exist and this downtime shows

Let me quote myself here: "we are unable to update it currently for the new IP `144.172.70.54:81` [...] We expect the domain to be updated soon, probably by tomorrow so the issue will be resolved by then"
I did not suggest that you should use this IP, I was merely pointing out the issue and that it is unrelated to the server being down but rather the domain being pointed at an outdated IP address. The change happened without a warning from our provider but is currently being resolved already.

>Downloading JARs and hosting them myself is bullshit and you know that, I just want to link from my documentation to your documentation reliably and not be a backup host for your server

"You can always download the jars from jcenter and host them yourself as a **backup** if our server goes down. However, this does not happen often since we switched hosts to a more reliable provider"

I suggested it as a _backup_ if you are so worried about our host going down, which is not a common event in the slightest.

**Comment by MinnDevelopment** [comment]
I am just going to point out that the domain has already been updated to the new IP in a AAAA record.
