### ISSUE TITLE
Getting the name of a ReactionEmote

### ISSUE THREAD

**Issue by stefan-reich** [DV8FromTheWorld/JDA#939]
Hi! This is for version 3.8.3.

In a MessageReactionAddEvent, I get a ReactionEmote object. It gives me the Unicode of the emoji, but that usually is not printed properly in console fonts etc.

Is there a way to get a clear-text name for the emoji?

Library working fine BTW.

Thanks

**Comment by binaryoverload** [comment]
There is no library method to get the name of a Unicode emoji. You would need to use a different library for that. Also, this issue would have been better bringing up in the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) as it's not really related to a library issue 😃

**Comment by stefan-reich** [comment]
Hey, thanks for the quick answer! I'll just find a list of those emojis then, right?

**Comment by stefan-reich** [comment]
OK, I think I found it. Thanks a lot.

https://github.com/amurani/unicode-emoji-list

**Comment by MinnDevelopment** [comment]
This is not part of the Discord API and cannot be fulfilled without a list of all emoji names. This list has not been made public by Discord and can thus not be implemented. Additionally, the unicode emoji do not have a 1:1 mapping to their aliases since Discord offers multiple aliases for the same emoji making it a non-bijective function.

**Comment by stefan-reich** [comment]
Not been made public? That's not so good. It'll be fine though, what I need is to classify emojis into positive and negative, and there's a learning algorithm behind it anyway. Thanks
