### ISSUE TITLE
NoSuchMethodError org.json

### ISSUE THREAD

**Issue by athenagame318** [DV8FromTheWorld/JDA#994]
I've been trying to run the JDA Discord, but I am getting: [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - There was an error in the WebSocket connection
java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;

I checked the GitHub issues, but none was able to help me.
I have the latest org.json version, so I do not know the cause..
This is my pom.xml: https://hasteb.in/agaseniz.xml
also does any of these libraries conflicts with org.json ? http://prntscr.com/nfdquv

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

- https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html
- https://stackoverflow.com/questions/35186/how-do-i-fix-a-nosuchmethoderror
- https://docs.oracle.com/javase/8/docs/api/java/lang/NoSuchMethodError.html
- Duplicate ot #716
